apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki 
  namespace: openshift-logging 
spec:
  size: 1x.small 
  storage:
    schemas:
    - version: v13
      effectiveDate: "2025-08-28"
    secret:
      name: logging-loki-s3 
      type: s3 
  storageClassName: nfs-client
  tenants:
    mode: openshift-logging 