kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-ocp
  namespace: minio-ocp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client
  volumeMode: Filesystem